apiVersion: v1
kind: Namespace
metadata:
  name: controller
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: controlelr-config
  namespace: controller
data:
  TASK_NAMESPACE: analytics
  BACKEND_HOST: http://backend.default.svc.cluster.local:5000
  KC_HOST: http://keycloak.identities.svc.cluster.local
  GIT_HOME: /data/git
  MOUNT_PATH: /data/controller
  PULL-POLICY: IfNotPresent
  KC_URL: http://keycloak.identities.svc.cluster.local
  KC_USER: admin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-operator
  namespace: controller
  labels:
    app: analytics-operator
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: analytics-operator
  template:
    metadata:
      labels:
        app: analytics-operator
    spec:
      serviceAccountName: analytics-operator
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: git
          persistentVolumeClaim:
            claimName: controller-pv-volclaim
      containers:
      - name: analytics-operator
        image: ghcr.io/aridhia-open-source/custom_controller:0.0.1-dev
        envFrom:
          - configMapRef:
              name: controller-config
        env:
          - name: KEYCLOAK_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: kc-secrets
                key: KEYCLOAK_ADMIN_PASSWORD
        resources:
          limits:
            cpu: 2000m
            memory: 1Gi
        volumeMounts:
          - name: git
            mountPath: /data/git
