apiVersion: v1
kind: Namespace
metadata:
  name: controller
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-operator
  namespace: controller
  labels:
    app: analytics-operator
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: analytics-operator
  template:
    metadata:
      labels:
        app: analytics-operator
    spec:
      serviceAccountName: analytics-operator
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: git
          persistentVolumeClaim:
            claimName: controller-pv-volclaim
      containers:
      - name: analytics-operator
        image: ghcr.io/aridhia-open-source/custom_controller:0.0.1-dev
        env:
          - name: TASK_NAMESPACE
            value: analytics
          - name: BACKEND_HOST
            value: http://backend.default.svc.cluster.local:5000
          - name: KC_HOST
            value: http://keycloak.identities.svc.cluster.local
          - name: GIT_HOME
            value: /data/git
          - name: MOUNT_PATH
            value: /data/controller
          - name: PULL-POLICY
            value: IfNotPresent
        resources:
          limits:
            cpu: 2000m
            memory: 1Gi
        volumeMounts:
          - name: git
            mountPath: /data/git
