apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: analytics.tasks.federatednode.com
spec:
  group: tasks.federatednode.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                image:
                  type: string
                user:
                  type: object
                  properties:
                    username:
                      type: string
                    email:
                      type: string
                project:
                  type: string
                dataset:
                  type: integer
  scope: Namespaced
  names:
    plural: analytics
    singular: analytic
    kind: Analytics
    shortNames:
    - at
