apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "pvControllerName" . }}
spec:
  storageClassName: controller-results
  accessModes:
    - ReadWriteMany
    - ReadOnlyMany
  capacity:
    storage: {{ .Values.storage.capacity }}
  {{- if .Values.storage.local }}
  local:
    path: {{ .Values.storage.local.path }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/os
          operator: In
          values:
          - linux
  {{- else if .Values.storage.azure }}
  azureFile:
    shareName: {{ .Values.storage.azure.shareName }}
    readOnly: false
    secretName: {{ .Values.storage.azure.secretName | default "azure-storage-secret" }}
  {{- else if .Values.storage.aws }}
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ include "awsStorageAccount" . }}
  {{- else if .Values.storage.nfs }}
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pvcControllerName" . }}
  namespace: {{ include "controller_ns" . }}
spec:
  storageClassName: controller-results
  volumeName: {{ include "pvControllerName" . }}
  resources:
    requests:
      storage: {{ .Values.storage.capacity }}
  accessModes:
    - ReadOnlyMany
