apiVersion: v1
kind: PersistentVolume
metadata:
  name: controller-pv
spec:
  storageClassName: controller-results
  accessModes:
    - ReadWriteMany
    - ReadOnlyMany
  capacity:
    storage: {{ .Values.storage.size }}
  {{ if .Values.storage.local }}
  local:
    path: {{ .Values.storage.local.path }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/os
          operator: In
          values:
          - linux
  {{ else if .Values.storage.azure }}
  azureFile:
    shareName: {{ .Values.storage.azure.shareName }}/results
    readOnly: false
    secretName: {{ .Values.storage.azure.secretName | default "azure-storage-secret" }}
  {{ else if .Values.storage.nfs }}
  {{ end }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: results-pusher-pv
spec:
  storageClassName: controller-results
  accessModes:
    - ReadWriteMany
    - ReadOnlyMany
  capacity:
    storage: {{ .Values.storage.size }}
  {{ if .Values.storage.local }}
  local:
    path: {{ .Values.storage.local.path }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/os
          operator: In
          values:
          - linux
  {{ else if .Values.storage.azure }}
  azureFile:
    shareName: {{ .Values.storage.azure.shareName }}/results
    readOnly: false
    secretName: {{ .Values.storage.azure.secretName | default "azure-storage-secret" }}
  {{ else if .Values.storage.nfs }}
  {{ end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: controller-pv-volclaim
  namespace: {{ include "controller_ns" . }}
spec:
  storageClassName: controller-results
  volumeName: controller-pv
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  accessModes:
    - ReadOnlyMany
