apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.controller }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-operator
  namespace: {{ .Values.namespace.controller }}
  labels:
    app: analytics-operator
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: analytics-operator
  template:
    metadata:
      labels:
        app: analytics-operator
    spec:
      serviceAccountName: analytics-operator
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: git
          persistentVolumeClaim:
            claimName: controller-pv-volclaim
      containers:
      - name: analytics-operator
        image: {{ template "fn-task-controller.image" . }}:{{ .Values.controller.tag | default .Chart.AppVersion }}
        envFrom:
          - configMapRef:
              name: controller-config
        env:
          - name: KEYCLOAK_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: kc-secrets
                key: KEYCLOAK_ADMIN_PASSWORD
          - name: KC_USER
            valueFrom:
              configMapKeyRef:
                name: keycloak-config
                key: KEYCLOAK_ADMIN
        resources:
          limits:
            cpu: 2000m
            memory: 1Gi
        volumeMounts:
          - name: git
            mountPath: {{ template "fn-task-controller.gitpath" . }}
