apiVersion: v1
kind: ConfigMap
metadata:
  name: controller-config
  namespace: {{ .Values.namespaces.controller }}
data:
  TASK_NAMESPACE: {{ .Values.namespaces.tasks }}
  NAMESPACE: {{ .Values.namespaces.controller }}
  BACKEND_HOST: http://backend.{{ .Release.Namespace }}.svc.cluster.local:5000
  KC_HOST: http://keycloak.{{ .Values.namespaces.keycloak }}.svc.cluster.local
  GIT_HOME: {{ template "fn-task-controller.gitpath" . }}
  MOUNT_PATH: {{ .Values.storage.local.path }}
  PULL-POLICY: IfNotPresent
  TAG: {{ .Values.controller.tag | default .Chart.AppVersion }}
  IMAGE: {{ template "fn-task-controller.image" . }}
