apiVersion: v1
kind: ConfigMap
metadata:
  name: controller-config
  namespace: {{ include "controller_ns" . }}
data:
  TASK_NAMESPACE: {{ include "tasks_ns" . }}
  NAMESPACE: {{ include "controller_ns" . }}
  BACKEND_HOST: http://backend.{{ .Release.Namespace }}.svc.cluster.local:5000
  KC_HOST: http://keycloak.{{ include "kc_ns" . }}.svc.cluster.local
  GIT_HOME: {{ template "fn-task-controller.gitpath" . }}
  MOUNT_PATH: {{ (.Values.storage.local).path }}
  PULL-POLICY: Always
  TAG: {{ .Values.controller.tag | default .Chart.AppVersion }}
{{- if .Values.global.taskReview }}
  TASK_REVIEW: enabled
{{- end }}
  IMAGE: {{ template "fn-task-controller.helper-image" . }}
  PUBLIC_URL: {{ .Values.global.host | default "federated-node" }}
{{- if .Values.storage.azure }}
  AZURE_STORAGE_ENABLED: "true"
  AZURE_SHARE_NAME: {{ .Values.storage.azure.shareName }}/controller
  AZURE_SECRET_NAME: {{ .Values.storage.azure.secretName | default "azure-storage-secret" }}
{{- end }}
