apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-operator
  namespace: {{ include "controller_ns" . }}
  labels:
    app: analytics-operator
  annotations:
    rollme: {{ template "rollMe" . }}
    helm.sh/hook-weight: "2"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: analytics-operator
  template:
    metadata:
      labels:
        app: analytics-operator
    spec:
      serviceAccountName: analytics-operator
      volumes:
        - name: git
          persistentVolumeClaim:
            claimName: {{ include "pvcControllerName" . }}
        - name: destinations
          configMap:
            name: controller-delivery-config
            items:
            - key: delivery.json
              path: delivery.json
      initContainers:
        - name: storage-init
          image: ghcr.io/aridhia-open-source/alpine:{{ .Values.fnalpine.tag | default "3.19" }}
          command: ["/bin/sh"]
          args:
            - -c
            - mkdir -p /mnt/storage/controller
          volumeMounts:
            - name: git
              mountPath: /mnt/storage
      containers:
      - name: analytics-operator
        image: {{ template "fn-task-controller.image" . }}:{{ .Values.controller.tag | default .Chart.AppVersion }}
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: controller-config
        env:
          - name: KC_USER
            valueFrom:
              configMapKeyRef:
                name: keycloak-config
                key: KEYCLOAK_ADMIN
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
        volumeMounts:
          - name: git
            mountPath: {{ template "fn-task-controller.gitpath" . }}
            subPath: controller
          - name: destinations
            mountPath: /app/controller/delivery.json
            subPath: delivery.json
