## This assumes the federated node being already deployed
# Basically duplicates the secret and kc-secret to the controller's
# namespace
## Should be only applied if it's a standalone installation
{{- if not .Values.global }}
{{- range list "kc-secrets" }}
{{ $secret := lookup "v1" "Secret" $.Release.Namespace . | default dict }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ . }}
  namespace: {{ include "controller_ns" $ }}
data:
{{- with $secret.data  }}
{{ toYaml . | indent 2 }}
{{- end }}
type: {{ $secret.type}}
---
{{- end }}
{{- range list "keycloak-config" }}
{{ $kccm := lookup "v1" "ConfigMap" $.Release.Namespace . | default dict }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ . }}
  namespace: {{ include "controller_ns" $ }}
data:
{{- with $kccm.data  }}
{{ toYaml . | indent 2 }}
{{- end }}
---
{{- end }}
{{- else if ((.Values.idp).github).secret_name }}
{{ $secret := lookup "v1" "Secret" $.Release.Namespace .Values.idp.github.secret_name | default dict }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.idp.github.secret_name }}
  namespace: {{ include "controller_ns" . }}
data:
{{- with $secret.data  }}
{{ toYaml . | indent 2 }}
{{- end }}
type: {{ $secret.type}}
---
{{- end }}
