## This assumes the federated node being already deployed
# Basically duplicates the secret and kc-secret to the controller's
{{- if not .Values.global -}}
{{- range list "keycloak-config" }}
{{ $kccm := lookup "v1" "ConfigMap" $.Release.Namespace . | default dict }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ . }}
  namespace: {{ include "controller_ns" $ }}
  annotations:
    helm.sh/hook: post-install, post-upgrade
data:
{{- with $kccm.data  }}
{{ toYaml . | indent 2 }}
{{- end }}
{{- end }}
---
{{- end }}
{{ $toCopy := list }}
{{- if .Values.global -}}
{{ $toCopy = append $toCopy "kc-secrets" }}
{{- end -}}

{{- if ((.Values.storage).azure).secretName }}
{{ $toCopy = append $toCopy ((.Values.storage).azure).secretName }}
{{- end }}
{{- if ((.Values.idp).github).secret_name }}
{{ $toCopy = append $toCopy ((.Values.idp).github).secret_name }}
{{- end }}
{{ range $toCopy }}
{{ $secret := lookup "v1" "Secret" $.Release.Namespace . | default dict }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ . }}
  namespace: {{ include "controller_ns" $ }}
  annotations:
    helm.sh/hook: post-install, post-upgrade
data:
{{- with $secret.data  }}
{{ toYaml . | indent 2 }}
{{- end }}
type: {{ $secret.type }}
---
{{- end }}
