## This assumes the federated node being already deployed
# Basically duplicates the secret and kc-secret to the controller's
{{- if not .Values.global -}}
{{- range list "keycloak-config" }}
{{- with include "lookupOrError" (dict "entity" "ConfigMap" "namespace" $.Release.Namespace "name" .) | fromYaml }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .metadata.name }}
  namespace: {{ include "controller_ns" $ }}
data:
{{ toYaml .data | indent 2 }}
{{- end }}
---
{{- end }}
{{- end }}
{{ $toCopy := list }}
{{- if not .Values.global -}}
{{ $toCopy = append $toCopy "kc-secrets" }}
{{- end -}}

{{- if ((.Values.storage).azure).secretName }}
{{ $toCopy = append $toCopy ((.Values.storage).azure).secretName }}
{{- end }}
{{- if ((.Values.idp).github).secret_name }}
{{ $toCopy = append $toCopy ((.Values.idp).github).secret_name }}
{{- end }}
{{- range $toCopy }}
{{- with include "lookupOrError" (dict "entity" "Secret" "namespace" $.Release.Namespace "name" .) | fromYaml }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .metadata.name }}
  namespace: {{ include "controller_ns" $ }}
data:
{{ toYaml .data | indent 2 }}
type: {{ .type }}
{{- end }}
---
{{- end }}
