## This assumes the federated node being already deployed
# Basically duplicates the regcred and kc-secret to the controller's
# namespace
## Should be only applied if it's a standalone installation
{{ if not .Values.global }}
{{- range list "kc-secrets" }}
{{ $regcred := lookup "v1" "Secret" $.Release.Namespace . | default dict }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ . }}
  namespace: {{ include "controller_ns" $ }}
data:
{{- with $regcred.data  }}
{{ toYaml . | indent 2 }}
{{- end }}
type: {{ $regcred.type}}
---
{{- end }}
{{- range list "keycloak-config" }}
{{ $kccm := lookup "v1" "ConfigMap" $.Release.Namespace . | default dict }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ . }}
  namespace: {{ include "controller_ns" $ }}
data:
{{- with $kccm.data  }}
{{ toYaml . | indent 2 }}
{{- end }}
---
{{- end }}
{{- end }}
