apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: analytics.tasks.federatednode.com
spec:
  group: tasks.federatednode.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-validations:
                - rule: "self.results.other.auth_type != 'AzCopy' && has(self.results.other.url) || has(self.results.other.auth)"
                  message: "url and auth are required field when auth_type is not AzCopy"
              required:
                - image
                - user
                - project
                - dataset
                - source
              properties:
                image:
                  type: string
                user:
                  type: object
                  properties:
                    username:
                      type: string
                    email:
                      type: string
                    idpId:
                      type: string
                project:
                  type: string
                dataset:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                source:
                  type: object
                  nullable: true
                  required:
                    - organization
                    - repository
                  properties:
                    branch:
                      type: string
                    organization:
                      type: string
                    repository:
                      type: string
                results:
                  type: object
                  oneOf:
                    - properties:
                      required: [ "git" ]
                    - properties:
                      required: [ "other" ]
                  properties:
                    git:
                      type: object
                      nullable: true
                      required:
                        - organization
                        - repository
                      allOf:
                        - not:
                            required:
                              - other
                      properties:
                        branch:
                          type: string
                        organization:
                          type: string
                        repository:
                          type: string
                    other:
                      type: object
                      nullable: true
                      properties:
                          url:
                            type: string
                          auth:
                            type: string
                          auth_type:
                            type: string
                      oneOf:
                      - required:
                          - url
                          - auth
                          - auth_type
                        oneOf:
                          - not:
                              required:
                                - git
                        properties:
                          url:
                          auth:
                            format: password
                          auth_type:
                            enum:
                              - Bearer
                              - Basic
                      - required:
                          - auth
                          - auth_type
                        oneOf:
                          - not:
                              required:
                                - git
                        properties:
                          url:
                          auth:
                            format: password
                          auth_type:
                            enum:
                              - AzCopy

  scope: Cluster
  names:
    plural: analytics
    singular: analytic
    kind: Analytics
    shortNames:
    - at
