## CM + Job template for Identity Provider initialization
# on keycloak with GitHub as a partner.
# If already set, it changes nothing

apiVersion: v1
kind: ConfigMap
metadata:
  name: idp-init-config
  namespace: {{ include "controller_ns" . }}
  annotations:
    helm.sh/hook-delete-policy: hook-succeeded
data:
  config.py: |-
{{ .Files.Get "scripts/idp-init.py" | indent 4 }}
---
{{- if (.Values.idp).github }}
apiVersion: batch/v1
kind: Job
metadata:
  name: idp-initializer
  namespace: {{ include "controller_ns" . }}
  annotations:
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "2"
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
    spec:
      restartPolicy: Never
      containers:
        - name: idp-initializer
          image: "{{ include "fn-task-controller.helper-image" . }}:{{ .Values.controller.tag | default .Chart.AppVersion }}"
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: controller-config
          env:
            - name: REPOSITORY
              value: {{ .Values.idp.github.orgAndRepo }}
            - name: KEYCLOAK_NAMESPACE
              value: {{ include "kc_ns" . }}
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kc-secrets
                  key: KEYCLOAK_ADMIN_PASSWORD
            - name: KEYCLOAK_GLOBAL_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: kc-secrets
                  key: KEYCLOAK_GLOBAL_CLIENT_SECRET
            - name: GITHUB_CLIENTID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.idp.github.secret_name }}
                  key: {{ .Values.idp.github.clientid_key }}
            - name: GITHUB_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.idp.github.secret_name }}
                  key: {{ .Values.idp.github.secret_key }}
{{- end }}
