## This assumes the federated node being already deployed
# Basically duplicates the regcred and kc-secret to the controller's
# namespace
{{- range list "regcred" "kc-secrets" }}
{{ $regcred := lookup "v1" "Secret" $.Release.Namespace . | default dict }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ . }}
  namespace: {{ $.Values.namespace.controller }}
data:
{{- with $regcred.data  }}
{{ toYaml . | indent 2 }}
{{- end }}
type: {{ $regcred.type}}
---
{{- end }}
{{- range list "keycloak-config" }}
{{ $kccm := lookup "v1" "ConfigMap" $.Release.Namespace . | default dict }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ . }}
  namespace: {{ $.Values.namespace.controller }}
data:
{{- with $kccm.data  }}
{{ toYaml . | indent 2 }}
{{- end }}
---
{{- end }}
