# Default values for fn-task-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
controller:
  tag:

namespaces:
  controller: fn-controller
  keycloak: keycloak
  tasks: tasks

storage:
  size: 1Gi
  azure:
    # secretName:
    # storageAccountName:
    # storageAccountKey:
    # shareName:
  nfs:
    # provisioner:
    # url:
    # path:
  local:
    # Local storage that will be shared with the backend
    # path:
    # Local storage that will be shared with the db
    # dbpath: /data/db

resources:
  limits:
    cpu: 200m
    memory: 1Gi

idp:
  github:
    secret_name:
    secret_key:
    clientid_key:

global: {}
  # host:
  # orgAndRepo:

delivery:
  github: {}
    # repository:
  other: {}
    # url
    # auth_type
