# Default values for fn-task-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace:
  controller: fn-controller
  keycloak: keycloak
  nginx: ingress-nginx
  tasks: tasks

controller:
  vol_path:

imagePullSecrets: regcred

storage:
  size: 100Mi
  local:
  azure:
  nfs:

idp:
  github:
    secret_name:
    secret_key:
    clientid_key:
