name: Build Docker Image
run-name: Building image
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  TAG: ${{ vars.VERSION }}
  IMAGE: custom_controller
  BUILD_PATH: .

jobs:
  build:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set Tag for dev branches
        if: github.ref != 'refs/heads/main'
        run: echo "TAG=${TAG}-${GITHUB_SHA::6}" >> ${GITHUB_ENV}

      # Need to get an ACR where to push the image
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_ACR }}
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >> ${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'
      - name: Build and push ${{ env.IMAGE }} image
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.BUILD_PATH }}
          file: ${{ env.BUILD_PATH }}/Dockerfile
          tags: ${{ vars.DOCKER_ACR }}/${{ env.OWNER_LC }}/${{ env.IMAGE }}:${{ env.TAG }}
          push: true
