name: Helm Chart Version Bump
run-name: Chart Bump
on:
  workflow_dispatch:
    inputs:
      new_version:
        description: New Chart version for the Helm Chart
        required: true

permissions:
  contents: write
  pull-requests: write

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  bump:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
      - name: Bump Chart.yaml
        run: |
          git checkout -b version-${{ inputs.new_version }}
          sed -i "s/version: .*/version: ${{ inputs.new_version }}/" k8s/fn-task-controller/Chart.yaml
          git config --global user.name 'BotMan'
          git config --global user.email 'r-casula@users.noreply.github.com'
          git commit -am "Version bumped to ${{ inputs.new_version }}"
          git push --set-upstream origin version-${{ inputs.new_version }}
          gh pr create \
            --title "Version bump to ${{ inputs.new_version }}" \
            --body "Automated version bump to ${{ inputs.new_version }}" \
            --base ${{ github.ref }}
