name: Helm Chart Version Bump
run-name: Chart Bump
on:
  workflow_dispatch:
    inputs:
      chartVersion:
        description: 'New Helm Chart version'
        required: true
        type: string
      appVersion:
        description: 'New tag the docker images are going to use'
        required: false
        type: string
      dryRun:
        description: 'Dry run, no changes committed. Shows the new Chart.yaml contents'
        required: false
        type: boolean
        default: true

permissions:
  contents: write

jobs:
  bump:
    uses: Aridhia-Open-Source/pipelines/.github/workflows/version-bump.yml@main
    with:
      chartVersion: ${{ inputs.chartVersion }}
      appVersion: ${{ inputs.appVersion }}
      dryRun: ${{ inputs.dryRun }}
      chartDir: k8s/fn-task-controller
